import 'package:pdf/pdf.dart';
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../domain/due_ledger_model.dart';
import '../../sales/domain/sale.dart';

class ReportGenerator {
  static const _htmlHead = '''
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@400;700&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Hind Siliguri', sans-serif; padding: 32px; font-size: 13px; color: #222; }
  h1 { font-size: 22px; text-align: center; margin-bottom: 2px; }
  h2 { font-size: 16px; margin-bottom: 6px; color: #333; }
  .center { text-align: center; }
  .subtitle { font-size: 14px; color: #444; }
  .date { font-size: 11px; color: #666; margin-bottom: 4px; }
  hr { border: none; border-top: 1px solid #ccc; margin: 10px 0; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { border: 1px solid #ddd; padding: 5px 8px; text-align: left; font-size: 11px; }
  th { background: #f0f0f0; font-weight: 700; }
  .summary-box { border: 1px solid #ccc; padding: 10px; margin-bottom: 16px; display: flex; justify-content: space-around; }
  .summary-col { text-align: left; }
  .summary-col .title { font-weight: 700; font-size: 13px; }
  .summary-col .detail { font-size: 11px; color: #555; }
  .text-right { text-align: right; }
  .text-green { color: #2e7d32; }
  .text-red { color: #c62828; }
  .bold { font-weight: 700; }
  .customer-block { margin-bottom: 14px; padding-bottom: 8px; border-bottom: 1px solid #eee; }
  .customer-header { display: flex; justify-content: space-between; margin-bottom: 4px; }
  .history-item { display: flex; justify-content: space-between; padding-left: 12px; font-size: 10px; color: #555; }
  .footer { margin-top: 24px; font-size: 9px; color: #999; display: flex; justify-content: space-between; border-top: 1px solid #eee; padding-top: 6px; }
</style>
</head>
<body>
''';

  static const _htmlTail = '''
<div class="footer">
  <span>Generated by Amar Dokan</span>
</div>
</body>
</html>
''';

  static String _escapeHtml(String text) {
    return text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
  }

  static Future<void> generateBakirKhataPDF({
    required String shopName,
    required Map<String, dynamic> summary,
    required List<CustomerDue> customers,
    required Map<int, List<CustomerTransaction>> transactionHistories,
  }) async {
    final num totalReceivable = summary['totalReceivable'] ?? 0.0;
    final num totalCollected = summary['totalCollected'] ?? 0.0;
    final num totalPayable = summary['totalPayable'] ?? 0.0;
    final num totalPaid = summary['totalPaid'] ?? 0.0;

    final html = StringBuffer(_htmlHead);
    html.writeln('<h1>${_escapeHtml(shopName)}</h1>');
    html.writeln('<p class="center subtitle">বাকির খাতা রিপোর্ট</p>');
    html.writeln('<p class="center date">তারিখ: ${DateFormat('dd MMMM yyyy').format(DateTime.now())}</p>');
    html.writeln('<hr>');

    // Summary
    html.writeln('<table><tr>');
    html.writeln('<td><span class="bold">মোট পাবো (বাকি):</span> ৳${totalReceivable.toStringAsFixed(0)}<br>');
    html.writeln('<span style="font-size:10px;color:#555;">আদায় হয়েছে: ৳${totalCollected.toStringAsFixed(0)}</span><br>');
    html.writeln('<span style="font-size:10px;color:#555;">বাকি আছে: ৳${totalReceivable.toStringAsFixed(0)}</span></td>');
    html.writeln('<td><span class="bold">মোট দিতে হবে:</span> ৳${totalPayable.toStringAsFixed(0)}<br>');
    html.writeln('<span style="font-size:10px;color:#555;">দিয়েছি: ৳${totalPaid.toStringAsFixed(0)}</span><br>');
    html.writeln('<span style="font-size:10px;color:#555;">বাকি দিতে হবে: ৳${totalPayable.toStringAsFixed(0)}</span></td>');
    html.writeln('</tr></table>');

    // Customer list
    html.writeln('<h2 style="margin-top:16px;">গ্রাহক তালিকা:</h2>');
    for (final customer in customers) {
      final history = transactionHistories[customer.id] ?? [];
      html.writeln('<div class="customer-block">');
      html.writeln('<div class="customer-header">');
      html.writeln('<div><span class="bold">${_escapeHtml(customer.name)}</span><br><span style="font-size:10px;color:#666;">ফোন: ${_escapeHtml(customer.phone ?? 'N/A')}</span></div>');
      html.writeln('<div class="text-red bold">৳${customer.currentCreditBalance.toStringAsFixed(0)}</div>');
      html.writeln('</div>');

      if (history.isNotEmpty) {
        html.writeln('<div style="font-size:10px;font-weight:700;margin-top:4px;">লেনদেন ইতিহাস:</div>');
        for (final trans in history.take(5)) {
          final isSale = trans.transactionType == 'sale';
          html.writeln('<div class="history-item">');
          html.writeln('<span>${DateFormat('dd/MM/yyyy').format(trans.transactionDate)} - ${isSale ? 'বাকি বিক্রয়' : 'টাকা পরিশোধ'}</span>');
          html.writeln('<span class="${isSale ? 'text-red' : 'text-green'}">৳${trans.amount.toStringAsFixed(0)}</span>');
          html.writeln('</div>');
        }
      }
      html.writeln('</div>');
    }
    html.writeln(_htmlTail);

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) => Printing.convertHtml(format: format, html: html.toString()),
      name: 'Bakir_Khata_Report_${DateFormat('dd_MMM_yyyy').format(DateTime.now())}.pdf',
    );
  }

  static Future<void> generateSalesPDF({
    required String shopName,
    required List<Sale> sales,
    required Map<String, dynamic> summary,
  }) async {
    final html = StringBuffer(_htmlHead);
    html.writeln('<h1>${_escapeHtml(shopName)}</h1>');
    html.writeln('<p class="center subtitle">বিক্রয় বিবরণী রিপোর্ট</p>');
    html.writeln('<p class="center date">তারিখ: ${DateFormat('dd MMMM yyyy').format(DateTime.now())}</p>');
    html.writeln('<hr>');

    // Summary
    html.writeln('<table><tr>');
    html.writeln('<td class="center"><div style="font-size:10px;color:#666;">মোট বিক্রি</div><div class="bold">৳${(summary['total'] ?? 0.0).toStringAsFixed(0)}</div></td>');
    html.writeln('<td class="center"><div style="font-size:10px;color:#666;">নগদ আদায়</div><div class="bold text-green">৳${(summary['cash'] ?? 0.0).toStringAsFixed(0)}</div></td>');
    html.writeln('<td class="center"><div style="font-size:10px;color:#666;">বাকি বিক্রি</div><div class="bold text-red">৳${(summary['credit'] ?? 0.0).toStringAsFixed(0)}</div></td>');
    html.writeln('</tr></table>');

    // Sales table
    html.writeln('<h2 style="margin-top:16px;">বিক্রির তালিকা</h2>');
    html.writeln('<table>');
    html.writeln('<tr><th>তারিখ</th><th>ইনভয়েস</th><th>গ্রাহক</th><th>ধরণ</th><th class="text-right">পরিমাণ</th></tr>');
    for (final sale in sales) {
      html.writeln('<tr>');
      html.writeln('<td>${DateFormat('dd/MM/yy').format(sale.saleDate)}</td>');
      html.writeln('<td>${_escapeHtml(sale.invoiceId)}</td>');
      html.writeln('<td>${_escapeHtml(sale.customerName ?? 'সাধারণ')}</td>');
      html.writeln('<td>${sale.paymentMethod == 'cash' ? 'নগদ' : 'বাকি'}</td>');
      html.writeln('<td class="text-right">৳${sale.totalAmount.toStringAsFixed(0)}</td>');
      html.writeln('</tr>');
    }
    html.writeln('</table>');
    html.writeln(_htmlTail);

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) => Printing.convertHtml(format: format, html: html.toString()),
      name: 'Sales_Report_${DateFormat('dd_MMM_yyyy').format(DateTime.now())}.pdf',
    );
  }
}
