import 'dart:io';
import 'package:excel/excel.dart';
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import '../../features/reports/domain/report_models.dart';
import '../../features/sales/domain/sale.dart';

class ReportExportService {
  static const _htmlHead = '''
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@400;700&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Hind Siliguri', sans-serif; padding: 32px; font-size: 13px; color: #222; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin-bottom: 8px; color: #333; }
  .subtitle { font-size: 12px; color: #666; margin-bottom: 8px; }
  hr { border: none; border-top: 1px solid #ccc; margin: 12px 0; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; font-size: 12px; }
  th { background: #f0f0f0; font-weight: 700; }
  .summary-row { display: flex; justify-content: space-between; margin-bottom: 16px; }
  .summary-item { text-align: center; flex: 1; }
  .summary-item .value { font-size: 16px; font-weight: 700; }
  .summary-item .label { font-size: 11px; color: #666; }
  .text-right { text-align: right; }
  .text-green { color: #2e7d32; }
  .text-red { color: #c62828; }
  .bold { font-weight: 700; }
  .footer { margin-top: 24px; font-size: 9px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 8px; }
</style>
</head>
<body>
''';

  static const _htmlTail = '''
<div class="footer">Generated by Amar Dokan</div>
</body>
</html>
''';

  static String _escapeHtml(String text) {
    return text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
  }

  static Future<void> exportProductReport(List<ProductReportItem> products, DateTime start, DateTime end) async {
    final dateRange = '${DateFormat('dd MMM, yyyy').format(start)} হতে ${DateFormat('dd MMM, yyyy').format(end)} পর্যন্ত';

    final html = StringBuffer(_htmlHead);
    html.writeln('<h1>আমার দোকান - বিক্রির রিপোর্ট</h1>');
    html.writeln('<p class="subtitle">সময়সীমা: $dateRange</p>');
    html.writeln('<hr>');
    html.writeln('<h2>বিস্তারিত পণ্য রিপোর্ট</h2>');
    html.writeln('<table>');
    html.writeln('<tr><th>পণ্য</th><th>পরিমাণ</th><th class="text-right">আয়</th><th class="text-right">লাভ</th></tr>');
    for (final p in products) {
      html.writeln('<tr>');
      html.writeln('<td>${_escapeHtml(p.productName)}</td>');
      html.writeln('<td>${p.quantitySold}</td>');
      html.writeln('<td class="text-right">${p.totalRevenue.toStringAsFixed(2)}</td>');
      html.writeln('<td class="text-right">${p.totalProfit.toStringAsFixed(2)}</td>');
      html.writeln('</tr>');
    }
    html.writeln('</table>');
    html.writeln(_htmlTail);

    await Printing.layoutPdf(
      onLayout: (format) => Printing.convertHtml(format: format, html: html.toString()),
      name: 'Product_Report',
    );
  }

  static Future<void> exportStockReport(List<Map<String, dynamic>> products) async {
    final html = StringBuffer(_htmlHead);
    html.writeln('<h1>আমার দোকান - স্টক রিপোর্ট</h1>');
    html.writeln('<p class="subtitle">তারিখ: ${DateFormat('dd MMM, yyyy').format(DateTime.now())}</p>');
    html.writeln('<hr>');
    html.writeln('<table>');
    html.writeln('<tr><th>নাম</th><th>স্টক</th><th class="text-right">ক্রয় মূল্য</th></tr>');
    for (final p in products) {
      html.writeln('<tr>');
      html.writeln('<td>${_escapeHtml(p['name'].toString())}</td>');
      html.writeln('<td>${p['current_stock']}</td>');
      html.writeln('<td class="text-right">৳${(p['purchase_price'] as num).toStringAsFixed(2)}</td>');
      html.writeln('</tr>');
    }
    html.writeln('</table>');
    html.writeln(_htmlTail);

    await Printing.layoutPdf(
      onLayout: (format) => Printing.convertHtml(format: format, html: html.toString()),
      name: 'Stock_Report',
    );
  }

  static Future<void> exportToPdf(SalesReportData data, List<Sale> sales, DateTime start, DateTime end) async {
    final dateRange = '${DateFormat('dd MMM, yyyy').format(start)} হতে ${DateFormat('dd MMM, yyyy').format(end)} পর্যন্ত';
    final stats = data.stats;

    final html = StringBuffer(_htmlHead);
    html.writeln('<h1>আমার দোকান - বিক্রির রিপোর্ট</h1>');
    html.writeln('<p class="subtitle">সময়সীমা: $dateRange</p>');
    html.writeln('<hr>');

    // Summary
    html.writeln('<h2>সারসংক্ষেপ</h2>');
    html.writeln('<div class="summary-row">');
    html.writeln('<div class="summary-item"><div class="value">${stats.salesCount}</div><div class="label">মোট বিক্রি</div></div>');
    html.writeln('<div class="summary-item"><div class="value">৳${stats.totalRevenue.toStringAsFixed(2)}</div><div class="label">মোট আয়</div></div>');
    html.writeln('<div class="summary-item"><div class="value">৳${stats.totalProfit.toStringAsFixed(2)}</div><div class="label">মোট লাভ</div></div>');
    html.writeln('<div class="summary-item"><div class="value">৳${stats.averageSale.toStringAsFixed(2)}</div><div class="label">গড় বিক্রয়</div></div>');
    html.writeln('</div>');

    // Top products
    html.writeln('<h2>বেশি বিক্রিত পণ্য</h2>');
    html.writeln('<table>');
    html.writeln('<tr><th>পণ্য</th><th>পরিমাণ</th><th class="text-right">আয়</th><th class="text-right">লাভ</th></tr>');
    for (final p in data.topProducts) {
      html.writeln('<tr>');
      html.writeln('<td>${_escapeHtml(p.productName)}</td>');
      html.writeln('<td>${p.quantitySold}</td>');
      html.writeln('<td class="text-right">${p.totalRevenue.toStringAsFixed(2)}</td>');
      html.writeln('<td class="text-right">${p.totalProfit.toStringAsFixed(2)}</td>');
      html.writeln('</tr>');
    }
    html.writeln('</table>');

    // Sales list
    html.writeln('<h2 style="margin-top:16px;">বিক্রির তালিকা</h2>');
    html.writeln('<table>');
    html.writeln('<tr><th>তারিখ</th><th>ইনভয়েস</th><th>ক্রেতা</th><th>ধরণ</th><th class="text-right">মোট টাকা</th></tr>');
    for (final s in sales) {
      html.writeln('<tr>');
      html.writeln('<td>${DateFormat('dd/MM/yy').format(s.saleDate)}</td>');
      html.writeln('<td>${_escapeHtml(s.invoiceId)}</td>');
      html.writeln('<td>${_escapeHtml(s.customerName ?? '-')}</td>');
      html.writeln('<td>${s.paymentMethod == 'cash' ? 'নগদ' : 'বাকি'}</td>');
      html.writeln('<td class="text-right">${s.totalAmount.toStringAsFixed(2)}</td>');
      html.writeln('</tr>');
    }
    html.writeln('</table>');
    html.writeln(_htmlTail);

    await Printing.layoutPdf(
      onLayout: (format) => Printing.convertHtml(format: format, html: html.toString()),
      name: 'Sales_Report_${DateFormat('dd_MM_yyyy').format(start)}_to_${DateFormat('dd_MM_yyyy').format(end)}',
    );
  }

  static Future<void> exportToExcel(SalesReportData data, List<Sale> sales, DateTime start, DateTime end) async {
    final excel = Excel.createExcel();

    // Summary Sheet
    final Sheet summarySheet = excel['Summary'];
    summarySheet.appendRow([TextCellValue('বিক্রির রিপোর্ট সারসংক্ষেপ')]);
    summarySheet.appendRow([TextCellValue('সময়সীমা'), TextCellValue('${DateFormat('dd/MM/yyyy').format(start)} - ${DateFormat('dd/MM/yyyy').format(end)}')]);
    summarySheet.appendRow([]);
    summarySheet.appendRow([TextCellValue('ম্যাট্রিক'), TextCellValue('মান')]);
    summarySheet.appendRow([TextCellValue('মোট বিক্রি'), IntCellValue(data.stats.salesCount)]);
    summarySheet.appendRow([TextCellValue('মোট আয়'), DoubleCellValue(data.stats.totalRevenue)]);
    summarySheet.appendRow([TextCellValue('মোট লাভ'), DoubleCellValue(data.stats.totalProfit)]);
    summarySheet.appendRow([TextCellValue('গড় বিক্রয়'), DoubleCellValue(data.stats.averageSale)]);

    // Sales List Sheet
    final Sheet salesSheet = excel['Sales List'];
    salesSheet.appendRow([
      TextCellValue('তারিখ'),
      TextCellValue('ইনভয়েস'),
      TextCellValue('ক্রেতা'),
      TextCellValue('ধরণ'),
      TextCellValue('মোট টাকা')
    ]);
    for (var s in sales) {
      salesSheet.appendRow([
        TextCellValue(DateFormat('dd/MM/yyyy').format(s.saleDate)),
        TextCellValue(s.invoiceId),
        TextCellValue(s.customerName ?? '-'),
        TextCellValue(s.paymentMethod),
        DoubleCellValue(s.totalAmount)
      ]);
    }

    // Save and Share
    final fileBytes = excel.save();
    if (fileBytes != null) {
      final directory = await getTemporaryDirectory();
      final file = File('${directory.path}/Sales_Report_${DateTime.now().millisecondsSinceEpoch}.xlsx');
      await file.writeAsBytes(fileBytes);

      await Share.shareXFiles([XFile(file.path)], subject: 'Sales Report Excel');
    }
  }
}
